server:
  port: 9080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/solrcloud?useSSL=false&characterEncoding=utf8
    username: root
    password: fengxiang

